### ISSUE TITLE
Desbloqueio de usuário e reset de senha

### ISSUE THREAD

**Issue by RossanoB** [Iniciativaz/zos-workshop#10]
Tentei efetuar o login com o ID Z00401 e aparece a seguinte mensagem:

IKJ56425I LOGON REJECTED, RACF TEMPORARILY REVOKING USER ACCESS
IKJ56418I CONTACT YOUR TSO ADMINISTRATOR

**Comment by billpereira** [comment]
Senha resetada para ZR1 novamente
