### ISSUE TITLE
Página do quiz fora. Time out

### ISSUE THREAD

**Issue by Viviaz** [Iniciativaz/zos-workshop#103]
Página do quiz retornando time out.
Pessoal, por favor, é possível prorrogar um pouco o prazo do quiz? Poderiam porrogar 1 dia a mais? Gostaria muito de obter o badge. 

![IMG_20200517_125735648](https://user-images.githubusercontent.com/65210593/82153585-aca35100-983e-11ea-9e9d-e8ae626b747e.jpg)

**Comment by lsalimena** [comment]
O sistema estava em janela de manutenção e já voltou.
