### ISSUE TITLE
Ambiente fora do ar - wc3270 retorna timeout

### ISSUE THREAD

**Issue by danieldamaso** [Iniciativaz/zos-workshop#109]
Tentei conectar ao ambiente z/OS do workshop entre 12h e 13h do domingo, mas obtive mensagem de timeout. Gostaria de poder enviar as respostas do quiz para obter o certificado. O prazo para envio das respostas será estendido? Qual a previsão de retorno do ambiente, por favor?

**Comment by lsalimena** [comment]
O sistema estava em janela de manutenção e já voltou.

**Comment by danieldamaso** [comment]
Já consegui postar as respostas, muito obrigado!
