### ISSUE TITLE
Reset senha Z00203

### ISSUE THREAD

**Issue by p4ndev** [Iniciativaz/zos-workshop#11]
Tentei antes de começar o evento e agora tbm e mesmo assim não estou conseguindo.

Obrigado

**Comment by billpereira** [comment]
Senha resetada para ZR1 novamente

**Comment by p4ndev** [comment]
O procedimento que estou fazendo: [Screencast](https://www.loom.com/share/baba6beced21484ea5503e273fe1b84b)

- Abro ele via PComm
- Digito o logon meu Z.....
- Digito a senha q me enviaram nos 2 campos
- Dps coloco minha senha no primeiro campo (4 itens)

Num vai... nao sei o que estou fazendo errado.

**Comment by p4ndev** [comment]
Desculpe, eu tenho que digitar 2 vezes a senha e nao estava fazendo isso.
Agora deu certo.

https://ibb.co/2tkMtf9
https://ibb.co/df7WdgG
https://ibb.co/T0cxMwm

Obrigado
