### ISSUE TITLE
Comentário sobre o quiz

### ISSUE THREAD

**Issue by danieldamaso** [Iniciativaz/zos-workshop#110]
Meu comentário: achei o nível das perguntas do quiz muito avançado para iniciantes no mundo mainframe e não achei justo atrelarem 70% de acerto para obtenção do certificado. O certificado é um comprovante de participação, mas exigir 70% isso é nível de alguns programas de certificação que formam especialistas. Achei o conteúdo do curso muito extenso, técnico demais, poderiam sintetizar mais, como um workshop introdutório, ou fazer versões do conteúdo diferentes para públicos distintos (devs, infra). Dar um tempo durante a apresentação para a execução assistida dos labs, e não depois. Afinal, foi feito em uma semana durante horário de trabalho. 5 horas diárias no horário do expediente é pesado, mesmo em home office. Fica como sugestões.

**Comment by lsalimena** [comment]
Oi, tudo bem. Antes de mais nada, agradecemos o feedback!
O badge corresponde a uma certificação e não um comprovante de participação. Para emissão do badge precisamos estabelecer uma regra e ela precisa ser a mesma mundialmente e isso, infelizmente, não conseguimos mudar. 
Sobre os demais comentários eu vou deixar anotado e validar com o time o que é possível melhorar para as próximas edições. 
Obrigada!!

**Comment by danieldamaso** [comment]
Ok, @lsalimena , obrigado pelo retorno, ficou mais claro o objetivo do badge. Tudo de bom pra vocês!
