### ISSUE TITLE
Sem acesso ao Sistema para submeter Qiz - ID Z00402

### ISSUE THREAD

**Issue by fabiozal** [Iniciativaz/zos-workshop#113]
Já foi bloqueado o acesso ao sistema C3270 ??

Estou tentando acesso para submeter o QIZ e não consigo mais acesso:

c3270 192.86.32.67
c3270 v3.6ga8 Wed May 13 19:10:45 UTC 2020 root

Copyright 1989-2019 by Paul Mattes, GTRC and others.
Type 'show copyright' for full copyright information.
Type 'help' for help information.

Trying 192.86.32.67, port 23...

**Comment by emerson-quinaia** [comment]
Boa tarde! Também estou com o mesmo problema, testei as 2 portas (23 e 1023) e ambas se encontram sem conexão.
Grato!

**Comment by lsalimena** [comment]
O sistema estava em janela de manutenção e já voltou.
