### ISSUE TITLE
Sem acesso ao quiz

### ISSUE THREAD

**Issue by z00533** [Iniciativaz/zos-workshop#117]
command TSO not found

**Comment by lsalimena** [comment]
Lembrando que o IP é o 192.86.32.67.
Pode verificar e dar retorno?

**Comment by z00533** [comment]
Sim
Faço logon normal, acesso os dataset dos labs...

**Comment by billpereira** [comment]
Oi @z00533 pode colar algum print aqui do erro?

**Comment by z00533** [comment]
Descobri, erro de dedo
Consegui submeter
De quanto em quanto tempo vcs estão submetendo os jobs de apuração de resultados

**Comment by lsalimena** [comment]
rodamos um score agora 11h20
