### ISSUE TITLE
Não consigo acessar o Quiz

### ISSUE THREAD

**Issue by z00507** [Iniciativaz/zos-workshop#122]
Meu usuário é Z00507
Meu nome é Cleber Alexandre de Oliveira
Na linha de comando eu digito TSO QUIZ
O sistema me responde dizendo que eu tenho que configura o prefixo de minha profile
tenho que enviar minhas respostas ...
meu zap é +31 98221-4004

**Comment by z00507** [comment]
z00507 commented now
Meu usuário é Z00507
Meu nome é Cleber Alexandre de Oliveira
Na linha de comando eu digito TSO QUIZ
O sistema me responde dizendo que eu tenho que configura o prefixo de minha profile
tenho que enviar minhas respostas ...
meu zap é +31 98221-4004

**Comment by billpereira** [comment]
Oi @z00507 você pode digitar primeiro esse comando:
TSO PROFILE PREFIX(z00507)

e ai tentar novamente o TSO QUIZ.. se não der certo pode colcar alguns print aqui?

**Comment by z00507** [comment]
Boa noite!
Antes de abrir está demanda, eu já tinha executado este comando, mas não
deu certo.  Vc disse q tem q ter alguns prints.

Em dom, 17 de mai de 2020 7:58 PM, billpereira <notifications@github.com>
escreveu:

**Comment by z00507** [comment]
digitei TSO PROFILE PREFIX (Z00507), Mas, nao deu certo.
Nao consigo enviar os displays


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em dom., 17 de mai. de 2020 às 19:58, billpereira <notifications@github.com>
escreveu:

**Comment by lsalimena** [comment]
Eu acabei de logar com o seu usuário e fiz o teste. Esta funcionando. 

TSO QUIZ 

Precisei resetar a sua senha para zr1. Troca ela assim que logar.
