### ISSUE TITLE
Pleas help me with my password

### ISSUE THREAD

**Issue by vrmartinezdlc** [Iniciativaz/zos-workshop#123]
Hi, i'm Victor,

Please help me to change my password, my user id is z00573

**Comment by vrmartinezdlc** [comment]
![image](https://user-images.githubusercontent.com/65518461/82204492-980c9a80-98ca-11ea-9847-b19d315c3d37.png)

**Comment by lsalimena** [comment]
Hi Victor. 
Password reset to ZR1
You need to change it when login
