### ISSUE TITLE
ID incorreto

### ISSUE THREAD

**Issue by dyegomichael** [Iniciativaz/zos-workshop#124]
recebi por nota informando que meu id é o Z00681. porém estou logando na plataforma com o id z00763 e validando o score com o mesmo.

**Comment by lsalimena** [comment]
Você se cadastrou 2x e conta pra mim os IDS z00681 e z00673. Esse z00763 que você passou não é seu. Esta alocado para o próximo curso. Você deu sorte que não tem ninguém usando. rs
Responde o quiz com o z00681 ou z00673, por favor. esses estão vinculados ao seu email.

**Comment by dyegomichael** [comment]
desculpe mencionei o id errado, no caso seria esse z00673.
