### ISSUE TITLE
Gente não e possível prorrogar o prazo do badge?

### ISSUE THREAD

**Issue by Viviaz** [Iniciativaz/zos-workshop#126]
Por favor, é possível extender o prazo do badge em 1 dia a mais visto que não e possível ter o arquivo com as respostas erradas e temos que verificar o arquivo quiz inteiro antes de submeter novamente? Para quem é iniciante não é simples as respostas. Obrigada

**Comment by lsalimena** [comment]
consegui prorrogar até 15h de hoje.
