### ISSUE TITLE
Esqueci a senha do TSO

### ISSUE THREAD

**Issue by pomamarco** [Iniciativaz/zos-workshop#127]
Bom dia!
Preciso de ajuda para resetar o meu logon no TSO. Tentei fazê-lo pelo Zih, mas recebo como resposta que não encontra meu id.

Parece que os dados que você me passou não correspondem aos que eu tenho no meu sistema. Isso pode ocorrer caso você seja um novo usuário e ainda não refletiu do meu lado :(

[9h05] Tente novamente mais tarde
Podem me ajudar?
Obrigado

**Comment by lsalimena** [comment]
qual o seu ID? 
O Zih não reseta a senha do ID do workshop.

**Comment by pomamarco** [comment]
Z00666

**Comment by pomamarco** [comment]
Oi Ludmila!

Não sei se você recebeu o meu id.

Z00666

**Comment by pomamarco** [comment]
Cliquei no botão errado e fechei a ussue

**Comment by lsalimena** [comment]
feito, ZR1
