### ISSUE TITLE
Sobre o workshop, badge e certificado

### ISSUE THREAD

**Issue by flagner** [Iniciativaz/zos-workshop#130]
Boa tarde,

Primeiro queria parabenizar a todos os envolvidos nessa ação, muito bom mesmo este workshop.
Entreguei o quiz, liberei a badge. Porém gostaria de saber se há como emitir algum tipo de certificado que eu possa apresentar ao RH da minha empresa (Serpro) para contabilizar no meu Curriculo.

**Comment by marcelokz** [comment]
O que eu fiz foi ir na opção Share Badge e escolhi o ícone da impressora (Print). Essa opção gera um PDF.

**Comment by flagner** [comment]
Muito bom, vou tentar isso. Muito obrigado.

**Comment by lsalimena** [comment]
A Márcia Maria é a ponto focal no SERPRO (ela fica em Salvador). Ela já esta trabalhando para ter o badge no sistema de vocês.
