### ISSUE TITLE
Por favor não postem o resultado ainda estou respondendo o quiz. Obrigada

### ISSUE THREAD

**Issue by Viviaz** [Iniciativaz/zos-workshop#131]
Por favor não postem o resultado ainda estou respondendo o quiz. Obrigada

**Comment by lsalimena** [comment]
o sistema ainda esta ativo então eu consigo rodar o score. Me avisa assim que acabar que eu vejo aqui

**Comment by lsalimena** [comment]
e ae, terminou?
