### ISSUE TITLE
Conclusão do QUIZ

### ISSUE THREAD

**Issue by z00507** [Iniciativaz/zos-workshop#132]
Recebi uma mensagem dizendo que eu não conclui o QUIZ com sucesso.
Para mim, eu tinha concluido.
Preciso saber o que devo fazer, pois parece que meu usuário foi revogado.
Tentei acessar o sistema com a minha senha, porém, agora estou me 
lembrando que uma pessoa da IBM mudou a senha para verificar o que estava ocorrendo na minha sessão.
Preciso concluir o QUIZ para retirar o certificado.
Ajudem-me.

**Comment by lsalimena** [comment]
você recebeu email com mais de um ID? O que pode ter acontecido é que você tem 2 IDs vinculados ao seu email. Completou por um deles.

**Comment by z00507** [comment]
Boa noite!Tentei entrar no TSO com meu usuário e senha.   Porém, fui revogado.Depois eu lembrei que uma pessoa da IBM tinha inicializado minha senha e alterado a mesma para analisar o problema que estava ocorrendo naminha máquina TSO (precisa de setar o prefixo da profile tso).Enfim, preciso que seja novamente inicializado minha senha para que eu possa entrar no sistema e concluir o  QUIZ.  Lembro-me que respondi todas as 60 questoes.Acredito que não tenha comandado a finalização após responder todas as questões - acho que era END.

Ou eu acredito que o fato da pessoa que inicializou a minha máquina tenha influenciado no meu QUIZ, pois acabei de ver que estou com a pontuação 0 e antes estava 50.

**Comment by z00507** [comment]
Não. Meu ID é Z00507

**Comment by z00507** [comment]
Reforçando, eu tinha respondido todas as questões (60). Acertei 50.  Estava aparecendo meu usuário com 50 questões como acerto.  Agora está aparecendo 0.  
Acredito que foi a reinicialização de meu ID.

**Comment by z00507** [comment]
Mas tenho minhas respostas em mãos .
Posso responder novamente.  Porem, minha senha foi revogada .

**Comment by lsalimena** [comment]
Acabei de olhar e seu dataset não tem nada. Resetei a senha para zr1. Acessa lá e me avisa assim que terminar de responder

**Comment by z00507** [comment]
Eu não me lembro de ter recebido.  Então, acredito q não.
Meu ID é Z00507

Em seg, 18 de mai de 2020 6:55 PM, Ludmila Salimena <
notifications@github.com> escreveu:

**Comment by z00507** [comment]
Vou acessar

**Comment by lsalimena** [comment]
ok, to de olho aqui.

**Comment by z00507** [comment]
OK. TERMINEI.

**Comment by z00507** [comment]
FICOU AGUARDANDO O RESULTADO

**Comment by lsalimena** [comment]
1 min

**Comment by lsalimena** [comment]
Desculpa a demora, entrei em call. * Z00507 Score: 50 
Parabéns!
