### ISSUE TITLE
Ludmila

### ISSUE THREAD

**Issue by maurocotia10** [Iniciativaz/zos-workshop#133]
Oi Ludmila, já respondi o quiz e consegui 37 acertos não foi suficiente. Precisava muito desta badge.

**Comment by TiagoNetwork** [comment]
Ola, Mauro

Eu conclui o quiz ( exame ) na madrugada de terca-feira 02:00 da manha. Tenta logar mais uma vez para realizar uma nova tentativa  do quiz, pois os nossos acessos e o servidor continuam em operacao.

**Comment by lsalimena** [comment]
ja atualizei o score, olha la. Ve se ja conseguiu
