### ISSUE TITLE
Envio do Quiz #Z00145

### ISSUE THREAD

**Issue by TiagoNetwork** [Iniciativaz/zos-workshop#137]
Boa noite / Bom dia

Eu gostaria de comunicar que  foi concluido o quiz nesta madrugada as 02:00 am

Estudante: Tiago De Oliveira
ID: Z00145

Obrigado a toda equipe que proporcionou este treinamento ( Ludimila, Phillip e o William )

**Comment by lsalimena** [comment]
Ja atualizei. Parabens! Conquistou seu badge. ;) Durante a semana você receberá email com detalhes.
