### ISSUE TITLE
Quiz finished

### ISSUE THREAD

**Issue by rodrigocgruiz** [Iniciativaz/zos-workshop#138]
ID Z00337

**Comment by lsalimena** [comment]
opa, rodei agora. PArabens!! conseguiu ;) * Z00337 Score: 43

**Comment by rodrigocgruiz** [comment]
Bom dia Ludmila
Obrigado, gostei muito do Workshop, me animou bastante, tanto que ja estou
inscrito em outros treinamentos.

Agora devo fazer mais alguma coisa para ? Para pegar o badge?

Em ter., 19 de mai. de 2020 às 18:09, Ludmila Salimena <
notifications@github.com> escreveu:
