### ISSUE TITLE
Conectando sem sucesso

### ISSUE THREAD

**Issue by Z00946** [Iniciativaz/zos-workshop#14]
[Doc1.pdf](https://github.com/Iniciativaz/zos-workshop/files/4610960/Doc1.pdf)
Estou tentando acessar o terminal porem so fica a mensagem conectando no rodape. Estou utilizando o pW3270.
Ainda nao consegui efetuar o login.
Configurei para conectar automatico e a tela só fica conforme anexo.

**Comment by AndreTorella** [comment]
Voce deve ter configurado o IP no menu REDE (superior), configurar host.
IP 192.86.32.67, Serviço(porta) 23.
Clique em conectar.
Se não conectar, basta fechar o PW3270 e abrir novamente que ele irá conectar automaticamente - se configurou assim, ou clique em conectar.

**Comment by Z00946** [comment]
OK. Obrigado. Eu consegui achar o erro.
