### ISSUE TITLE
Atualização do quiz

### ISSUE THREAD

**Issue by GuilhermeMtSouza** [Iniciativaz/zos-workshop#142]
Boa noite gostaria de avisar que acabei de submeter meu quiz por completo cujo ID é Z00379, desde já obrigado.

**Comment by lsalimena** [comment]
olha la

**Comment by GuilhermeMtSouza** [comment]
Boa noite, gostaria de saber se isso significa que consegui? Kkk

Att Guilherme

De: Ludmila Salimena <notifications@github.com>
Enviada em: terça-feira, 19 de maio de 2020 18:56
Para: Iniciativaz/zos-workshop <zos-workshop@noreply.github.com>
Cc: Guilherme Matheus de souza <gui_souza_15@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [Iniciativaz/zos-workshop] Atualização do quiz (#142)


olha la
