### ISSUE TITLE
QUIZ - Workshop z/OS-Workshop

### ISSUE THREAD

**Issue by liciniovr** [Iniciativaz/zos-workshop#143]
bom dia,
o gabarito do quiz será divulgado?
Gostaria de verificar o que errei, onde errei e porque errei.
Agradeço

**Comment by lsalimena** [comment]
Oi! não podemos compartilhar o gabarito. Se interessar, você pode se cadastrar para a classe de julho (em inglês) e rever o conteúdo ou refazer o quiz. ibm.biz/zOSclass
