### ISSUE TITLE
É  possivel submeter o quiz  ainda hoje ?

### ISSUE THREAD

**Issue by Viviaz** [Iniciativaz/zos-workshop#144]
É  possivel submeter o quiz  ainda hoje ? Obrigada

**Comment by lsalimena** [comment]
Oi, não é mais possível. Ambiente já está indisponível. Você poderá participar da classe de julho (em inglês) e submeter o quiz novamente nessa oportunidade :) se cadastra em ibm.biz/zOSclass

**Comment by Viviaz** [comment]
Farei isso . Obrigada

Em qui, 21 de mai de 2020 11:59, Ludmila Salimena <notifications@github.com>
escreveu:
