### ISSUE TITLE
Aceitar a badge

### ISSUE THREAD

**Issue by romuloaribeiro** [Iniciativaz/zos-workshop#146]
Boa tarde,

Fiz o curso com o e-mail corporativo, porém ao clicar em aceitar a badge ele me da o erro de que minha conta no acclaim está com um e-mail não verificado.

Já pedi para reenviar o e-mail de verificação várias vezes, porém nunca chega. Acredito que os e-mails da acclaim estão sendo bloqueados.

Meu pedido é para saber se é possível enviar essa badge para o meu e-mail pessoal.

**Comment by lsalimena** [comment]
Oi!! Hoje de manhã a sua empresa liberou o dominio do acclaim. Esta sendo barrado pelo firewall. Tenta novamente por favor. Ja deve ter normalizado :)
