### ISSUE TITLE
usuário TSO revogado

### ISSUE THREAD

**Issue by thiagosilasmatos** [Iniciativaz/zos-workshop#147]
Prezados, Boa noite, será que consigo enviar mais um quiz para tentar melhorar minha pontuação?

**Comment by lsalimena** [comment]
Oi, não será possível. Ambiente não está mais disponível. 
Caso não tenha conseguido conquistar o badge eu sugiro que se matricule na turma de julho (em inglês) - ibm.biz/zOSclass
