### ISSUE TITLE
Timeout ao conectar no zOS

### ISSUE THREAD

**Issue by wprighi** [Iniciativaz/zos-workshop#15]
Estou tentando conectar via wc3270 e estou tendo timeouts:

![image](https://user-images.githubusercontent.com/65185135/81590149-c2250080-9390-11ea-9ae5-2c74b49f8ee8.png)

**Comment by billpereira** [comment]
Tentou pingar o endereço? Pode ser uma limitação da rede que você está.

**Comment by wprighi** [comment]
Ping vai, telnet na porta 23 não, 3270 usa essa porta 23 mesmo?
Telnet na porta 22 tb funciona.

![image](https://user-images.githubusercontent.com/65185135/81600383-e5a37780-939f-11ea-899a-efa4400cb99c.png)

**Comment by billpereira** [comment]
Isso, essa mesma, teve uma pessoa que comentou que essa porta era bloqueada nos provedores da cidade dela, não sei se é o caso :/ mas eu tenho um workaround se você não conseguir, pode tentar utilizando o zowe Preciso ver se está habilitado para essa lpar.

**Comment by billpereira** [comment]
Oi você pode tentar com a porta 1023?

**Comment by billpereira** [comment]
Porta 1023 também habilitada
