### ISSUE TITLE
Reset password usuário Z00604

### ISSUE THREAD

**Issue by SanderDallOrto** [Iniciativaz/zos-workshop#16]
Por favor reset a password do usuário z00604. 

Obrigado,
Sander Campo DallOrto

**Comment by billpereira** [comment]
password reset para a senha inicial zr1

**Comment by SanderDallOrto** [comment]
continua dando IKJ56474I USERID OR PASSWORD IS INCORRECT OR NOT AUTHORIZED

**Comment by billpereira** [comment]
Oi Sander, eu acabei de testar e está funcionando, pode confirmar o ip que está usando a conexão?
![image](https://user-images.githubusercontent.com/38498198/81597044-6dd34e00-939b-11ea-89c7-00ba8cdd9f1d.png)
