### ISSUE TITLE
SENHA USERID Z00170

### ISSUE THREAD

**Issue by biancamaluf** [Iniciativaz/zos-workshop#18]
SENHA INCORRETA

**Comment by billpereira** [comment]
senha é ZR1, pode confirmar o ip que está tentando conectar?
![image](https://user-images.githubusercontent.com/38498198/81597132-9a876580-939b-11ea-8fd2-8ae7f230187c.png)

**Comment by biancamaluf** [comment]
192.86.32.91

**Comment by billpereira** [comment]
Oi Bianca, esse é o IP do master the mainframe e não da lpar que estamos utilizando, você deve usar o ip 192.86.32.57 que foi no e-mail :D

**Comment by biancamaluf** [comment]
192.86.32.67
