### ISSUE TITLE
Lista arquivos ou diretórios

### ISSUE THREAD

**Issue by reinaldosaraiva** [Iniciativaz/zos-workshop#20]
Tentei lista arquivos ou diretório com comando dir, apareceu a mensagem de erro abaixo.

ftp> dir
200 Port request OK.
425 Unable to open data connection.
ftp>

**Comment by billpereira** [comment]
tenta novamente, mas antes digite o comando: passive

**Comment by reinaldosaraiva** [comment]
Tentei novamente mensagem que aparece agora "Comando inválido"

**Comment by Fabianobarros81** [comment]
o comando no MS-DOS é: quote pasv 

mas não funcionou pra mim tbm... o certo é migrar pra Linux, kkk

**Comment by AndreTorella** [comment]
No meu computador, quando fiz o comando DIR via FTP a primeira vez, foi solicitado autorização do Firewall do Windows. Eu permiti e funcionou normalmente.

**Comment by Fabianobarros81** [comment]
Pode ser que seja relacionado alguma versão do Windows, eu tenho Windows e Linux na minha maquina acabei que nem tentei muito no Windows.

**Comment by reinaldosaraiva** [comment]
Testei com Linux e ferramenta WINSCP com sucesso
