### ISSUE TITLE
Recebi 2 ID. 

### ISSUE THREAD

**Issue by z00160** [Iniciativaz/zos-workshop#32]
Estava usando o primeiro ID para os exercicios, depois recebi novo ID. Qual est[a valendo

**Comment by billpereira** [comment]
@lsalimena

**Comment by billpereira** [comment]
Oi você pode seguir com qualquer um dos dois, mas tente completar todas as atividades com o mesmo

**Comment by z00160** [comment]
Ok.
A Ludmila respondeu para eu ficar com o primeiro mesmo.
Obrigada.

Em ter, 12 de mai de 2020 11:43, billpereira <notifications@github.com>
escreveu:

**Comment by billpereira** [comment]
maravilha... fechando o issue...
