### ISSUE TITLE
Usuário Z00567 acesso negado

### ISSUE THREAD

**Issue by emerson-quinaia** [Iniciativaz/zos-workshop#36]
Bom dia! 
Conforme o guia baixei o terminal wc3270 para windows 10, após segui os passos e criei a nova sessão e enfim ele criou o MtM, que acesso ao TSO, ao tentar entrar no TSO digito o usuário, porém após a hora que digito a senha o mesmo retorna usuário negado.

Grato!

**Comment by billpereira** [comment]
Oi Emerson, confere o IP que você está usando se é o 192.86.32.67
