### ISSUE TITLE
Lab02

### ISSUE THREAD

**Issue by pazzi** [Iniciativaz/zos-workshop#42]
Após executar os passos do item 1 do lab2
e executar a sequencia *=sd;owner z00055 ;st *    
Não consigo ver a saída do job

Obs.: Meu id é *z00055*

**Comment by Fabianobarros81** [comment]
cara, lá em =sd;st tente executar os seguintes comandos

prefix *
owner *
dest
st

depois vc pode filtrar os jobs por owner z00151

se não funcionar dentro ainda de =st;st
vai com o cursor até a letra F em Filter tecle enter e depois na opção 3 coloque o seu ID ou o *

tenta ai e nos fala, boa sorte.

**Comment by pazzi** [comment]
Obrigado Fabiano!
Entrei em =sd;st e executei o "prefix *" e as saídas dos jobs apareceram!
Obrigado pela força.

**Comment by Fabianobarros81** [comment]
sucesso!!
