### ISSUE TITLE
LAB 2.4

### ISSUE THREAD

**Issue by fhca02** [Iniciativaz/zos-workshop#44]
NO ultimo exercício do lab2 pede para consertar o erro, mais não sei exatamente o que esta errado

![image](https://user-images.githubusercontent.com/14085111/81729728-d6393280-9462-11ea-86eb-a74dfc317965.png)

![image](https://user-images.githubusercontent.com/14085111/81729599-9f631c80-9462-11ea-8067-713701a6a7da.png)

**Comment by Fabianobarros81** [comment]
a virgula depois do IEFBR14 é desnecessária

**Comment by billpereira** [comment]
O @Fabianobarros81 já deu o spoiler :D 

Mas aproveitando que temos as imagens,  perceba que no output as linhas do job tem um numero, você pode utilizar esses números para se localizar. Quando vai para o final tem as mensagens referentes ao JCL error, se olhar ela tbm começa com um número, e está dizendo que esperava uma continuação e não recebeu, justamente por causa da vírgula ele achava que você iria passar mais parametros mas foi direto para o próximo step ;)
