### ISSUE TITLE
Password ou usuário com erro...

### ISSUE THREAD

**Issue by liciniovr** [Iniciativaz/zos-workshop#45]
quando acesso o wc3270 e tento logar z00521 pass zr1
recebo a msg de erro na senha..

Entro com o comando TSO e ele pede usuário e senha e recebo o mesmo erro.
meu e-mail: licinio-vilac.moreira@serpro.gov.br
alternativo: lvrmoreira@gmail.com (o e-mail para o serpro está caindo na caixa de spam...)

**Comment by billpereira** [comment]
Oi, confirme o IP, 192.86.32.67 o correto
