### ISSUE TITLE
LAB 2

### ISSUE THREAD

**Issue by buenojrr** [Iniciativaz/zos-workshop#46]
Olá,
estou dando o SUB nos jobs porem não esta aparecendo a SYSOUT.
aparece que o JOB foi submetido mas não volta nenhum RC.
ID Z00151

**Comment by Fabianobarros81** [comment]
cara, lá em =sd;st tente executar os seguintes comandos

prefix * <enter>
 owner * <enter>
 dest <enter>
 st <enter>

depois vc pode filtrar os jobs por owner z00151

se não funcionar dentro ainda de =st;st 
vai com o cursor até a letra F em Filter tecle enter e depois na opção 3 coloque o seu ID ou o *

tenta ai e nos fala, boa sorte.
