### ISSUE TITLE
Não estou conseguindo configurar e acessar o emulador de TN3270

### ISSUE THREAD

**Issue by rhayannematos** [Iniciativaz/zos-workshop#47]
Olá, estou com dificuldade em acessar o sistema, assisti os tutoriais e ainda me parece um pouco confuso, parece que algumas coisas não estão funcionando direito e eu não sei se realmente estou com dificuldades ou é meu notebook que está com algum problema em relação a instalação. Hoje não pude assistir a aula completamente por problemas na minha internet e estou um pouco perdida, se alguém puder me ajudar, ficaria muito grata.

Agradeço desde já pela atenção!

**Comment by Fabianobarros81** [comment]
Explica mais sobre o seu problema, voce instalou o TN3270?

tenta assistir esse vide e vê se consegue https://youtu.be/qu4q_B9PzL8 senão reporta aqui novamente, ok?

boa sorte ai

**Comment by rhayannematos** [comment]
Fiz novamente com mais calma e consegui, muito obrigada!
