### ISSUE TITLE
Não estou conseguindo instalar, configurar e acessar o emulador x3270 no MAC Catalina 10.15.4

### ISSUE THREAD

**Issue by fabiozal** [Iniciativaz/zos-workshop#48]
Segui os procedimentos do link http://mtm2019.mybluemix.net/connectivity_guide/connectivity_guide_software.html
e do Youtube: https://www.youtube.com/watch?v=lKLkqsKTo3Y

e não consegui instalar o emulador x3270.

tentei executar o script install_c3270.sh porém ocorre erros conforme abaixo:

Mac-FabioZal:Downloads mackfz$ sudo zsh install_c3270.sh
Password:
install_c3270.sh:26: parse error near `softwareupdate'
Mac-FabioZal:Downloads mackfz$

O script (anexo -- renomei a extensão de .sh para .txt para anexar aqui) não prossegue a instalação, acredito que estou errando em algo.

[install_c3270.txt](https://github.com/Iniciativaz/zos-workshop/files/4619341/install_c3270.txt)

Poderiam me auxiliar para conseguir instalar o emulador ??
Alguém que utilizar MAC Catalina 10.15.4 conseguiu instalar ??

OBS: Tenho instalado no MAC o XCODE 11.4.1

**Comment by Fabianobarros81** [comment]
Cara, achei esse video https://www.reddit.com/r/mainframe/comments/gd5uxz/x3270_for_macos_catalina/

ve se ajuda, sem compromisso ok?

**Comment by alexantao** [comment]
Eu instalei o meu c3270, é simples mas funciona, ó stem que ter Xcode, se não me engana:
https://medium.com/@decadentsz/tn3270-on-macos-catalina-connect-to-ibm-mainframe-easily-58a97b4bc37b

**Comment by billpereira** [comment]
Tem uma versão free tambem do 3270 na app store, só que tem algumas limitações como timeout e functions keys, mas acredito que seja um workaround... as dicas do @alexantao e do @Fabianobarros81 ajudaram?

**Comment by alexantao** [comment]
Se tudo mais falhar, ainda tem um cliente chamado Mocha, tem 30 dias de trial. Só procurar e instalar, pacote pronto para o MacOSX

**Comment by fabiozal** [comment]
Obrigado pelas informações. 

Consegui instalar o c3270 através do link informado acima do @alexantao !!

Notei que estava faltando o  XCode Command Line Tools que acabei instalando !!!

Já acessei o c3270 e alterei minha senha.

Valeu também pelas dicas dos APPs.

Muito obrigado !!
