### ISSUE TITLE
Preciso resetar a senha

### ISSUE THREAD

**Issue by AVMRJ** [Iniciativaz/zos-workshop#49]
Bom dia. Utilizei um número maior de caracteres que permitido ao criar a senha e tive um "password revoked". Peço instruções para recuperar ou gerar nova senha. Grato!

**Comment by billpereira** [comment]
qual id? :D

**Comment by AVMRJ** [comment]
A id é: Z00392 . Obrigado

Em qua., 13 de mai. de 2020 às 10:34, billpereira <notifications@github.com>
escreveu:

**Comment by billpereira** [comment]
feito, password zr1
