### ISSUE TITLE
Problema no login 3270

### ISSUE THREAD

**Issue by ronanbss** [Iniciativaz/zos-workshop#50]
Bom dia. Não consigo realizar o meu login no ambiente 3270.

Consigo entrar na tela de login, digito corretamente a senha e vou para próxima tela. Nessa nova tela fica carregando e depois sou desconectado.

ID - Z00562

**Comment by billpereira** [comment]
Password novamente em ZR1, parece mais um problema de conexão pode colar alguns prints aqui?

**Comment by ronanbss** [comment]
Com o reset foi possível realizar o login novamente, muito obrigado!

**Comment by Emanuelzos** [comment]
Bill, tem como "resetar" minha senha tb ?? Fui logar novamente agora e foi rejeitado. 

ID: Z00730

**Comment by billpereira** [comment]
feito @Emanuelzos
