### ISSUE TITLE
MXI

### ISSUE THREAD

**Issue by andersonnobre76** [Iniciativaz/zos-workshop#55]
como posso ter acesso ao comando TSO MXI ?

**Comment by philippeleite** [comment]
O MXI pode ser encontrado no site http://www.cbttape.org/cbtdowns.htm nos files 409 e 410.
A documentação para instalação está no file 409 no membro $INSTALL. 
Os arquivos estão em formato XMIT e deverão ser transferidos via FTP em formato binário.
Para fazer a instalação completa será necessário autorizações especiais no z/OS.
