### ISSUE TITLE
Lab05 passo 2 Idcams

### ISSUE THREAD

**Issue by pazzi** [Iniciativaz/zos-workshop#56]
No lab05 item 2 "2. Create VSAM data set using sequential data set input"...
Está dando o seguinte erro no output do JES:
 
 _DEFINE_ CLUSTER ( NAME ( Z00055.VSAM   ) -                             
            VOLUME(VPWRKB) TRACKS(15) RECORDSIZE(170,170) -             
            NONINDEXED REUSE SHAREOPTIONS(2) SPANNED SPEED -            
            CONTROLINTERVALSIZE(4096) )                                 
***IDC3020I  UNABLE TO ALLOCATE SPACE ON USER VOLUME ***                      
IDC3009I ** VSAM CATALOG RETURN CODE IS 68 - REASON CODE IS IGG0CLEW-20 
IDC3003I FUNCTION TERMINATED. CONDITION CODE IS 12 _  

Voces teriam que intervir, ou temos meios para resolver o problema?

**Comment by wfazolato** [comment]
O mesmo erro ocorreu comigo.

**Comment by pazzi** [comment]
Agora está passando!!
