### ISSUE TITLE
Lab 01 - Putty

### ISSUE THREAD

**Issue by PollyEler** [Iniciativaz/zos-workshop#57]
Qdo digito o comando ocorre a mensagem no prompt após o Ready 
![20200513_171448](https://user-images.githubusercontent.com/65312177/81861992-69479a80-953f-11ea-875b-e36ee6978043.jpg)
"Command id not found"

**Comment by billpereira** [comment]
A conexão pelo putty, não é na porta 23, você precisa usar a porta 22, para conectar direto no ssh

**Comment by PollyEler** [comment]
Muito Obrigada! 😉
