### ISSUE TITLE
Usuário já logado

### ISSUE THREAD

**Issue by alexantao** [Iniciativaz/zos-workshop#59]
Minha sessão travou e tive que fechar "na marra". A conexão ficou presa e não consigo mais me logar pois diz que o usuário já está logado. Tem como matar a sessão para mim ? Z00446
obrigado

**Comment by billpereira** [comment]
tem uma opcao na tela de login onde tem varios campos, usuario, password... escrito reconnect, só colocar um S na frente... porém depois de um tempo tem timeout... provavelmente agora ja teve o timeout :D
