### ISSUE TITLE
ID TEMPORARILY REVOKING USER ACCESS

### ISSUE THREAD

**Issue by marcusant** [Iniciativaz/zos-workshop#6]
Tentei efetuar o login com o ID Z00328 e aparece a seguinte mensagem:

 IKJ56425I LOGON REJECTED, RACF TEMPORARILY REVOKING USER ACCESS   
 IKJ56418I CONTACT YOUR TSO ADMINISTRATOR                          
 ******                                                            
                                                                   
Poderia me indicar o que fazer, por favor?
Obrigado

**Comment by billpereira** [comment]
Senha resetada para ZR1 novamente
