### ISSUE TITLE
LAB 03 - Problemas em visualizar OUTPUT 

### ISSUE THREAD

**Issue by dovallefvo** [Iniciativaz/zos-workshop#60]
Meu OUTPUT no SDSF parece estar sempre apontando para o JOB, mesmo submetendo conforme o passo a passo do LAB 03. Peço auxílio nesse problema.
Veja  as imagens:
![Lab2Proc1](https://user-images.githubusercontent.com/65181695/81929545-920e7500-95bd-11ea-968d-8d1d965defe0.PNG)

![Lab2Proc2](https://user-images.githubusercontent.com/65181695/81929577-a2265480-95bd-11ea-8435-7211c15ac8e2.PNG)

![Lab2Proc3](https://user-images.githubusercontent.com/65181695/81929609-b2d6ca80-95bd-11ea-82bd-0fe3cd65ca7e.PNG)

![Lab2Proc4](https://user-images.githubusercontent.com/65181695/81929622-b8341500-95bd-11ea-8830-893c9dcd863f.PNG)

![Lab2Proc5](https://user-images.githubusercontent.com/65181695/81929635-bf5b2300-95bd-11ea-87e5-934b7b30b40c.PNG)

![Lab2Proc6](https://user-images.githubusercontent.com/65181695/81929654-c4b86d80-95bd-11ea-8f83-f6234e87599e.PNG)

![Lab2Proc7](https://user-images.githubusercontent.com/65181695/81929678-ce41d580-95bd-11ea-9f3d-e7326735b86e.PNG)

**Comment by wfazolato** [comment]
Veja se não existe um filtro. Eu estava com o mesmo problema.

**Comment by billpereira** [comment]
Oi, repara que quando você submete o job, vc recebe uma mensagem com o id 03272, e o que você tentou ver tem 03249 e é um TSU, o que vc abriu é o seu usuario, tente dar esse comando: owner z00653 pre *

deve trazer todas entradas e você vai conseguir ver o correto! Obrigdo pelos prints! :D

**Comment by dovallefvo** [comment]
> Oi, repara que quando você submete o job, vc recebe uma mensagem com o id 03272, e o que você tentou ver tem 03249 e é um TSU, o que vc abriu é o seu usuario, tente dar esse comando: owner z00653 pre *
> 
> deve trazer todas entradas e você vai conseguir ver o correto! Obrigdo pelos prints! :D

Muito obrigado pela resposta ;-D . Estava faltando um detalhe na sintaxe, quebrei a cabeça aqui e consegui fazer funcionar, o correto é:
`owner z00653;pre *`

![Lab2Proc8](https://user-images.githubusercontent.com/65181695/81961439-c3506a80-95e8-11ea-96a4-b3cb77454713.PNG)

![Lab2Proc9](https://user-images.githubusercontent.com/65181695/81961452-c9464b80-95e8-11ea-8080-97a222cdd49b.PNG)

**Comment by dovallefvo** [comment]
Muito obrigado billPereira
