### ISSUE TITLE
Lab 5 Parte 7

### ISSUE THREAD

**Issue by fabiocosta0305** [Iniciativaz/zos-workshop#62]
Consegui corrigir um problema, mas o RC ainda não zerou (mudando de 8 para 4)

    109  IGYCB7310-W   The "PERFORM" statement at "PERFORM (line 109.1)" cannot reach its exit.

O JOBNUMBER que gerou esse último retorno é o JOB03578

**Comment by PollyEler** [comment]
Qual foi o erro que nao permite executar o Step2?

**Comment by fabiocosta0305** [comment]
É esse... Na verdade tem um outro antes, mas depois que você o corrige, aparece esse

**Comment by EddieCavic** [comment]
Basta comentar a linha do comando perform que ira funcionar, colocando um * na coluna 7.

**Comment by billpereira** [comment]
deu certo @fabiocosta0305 ?

**Comment by fabiocosta0305** [comment]
Acabei não testando

**Comment by fabiocosta0305** [comment]
Deu certo, acabei de testar. JOB05796
