### ISSUE TITLE
Há tempo de logoff?

### ISSUE THREAD

**Issue by AVMRJ** [Iniciativaz/zos-workshop#64]
Bom dia,
Há tempo de logoff automático em caso de queda de conexão? 
Obrigado.

**Comment by wfazolato** [comment]
Faça logon novamente e selecione a opção Reconect na tela de logon.

**Comment by billpereira** [comment]
Sim tem timeout, mas a opção que o @wfazolato mencionou permite vc retornar sem precisar esperar o timeout
