### ISSUE TITLE
Reset de sessão

### ISSUE THREAD

**Issue by flagner** [Iniciativaz/zos-workshop#66]
Bom dia,

Favor resetar minha sessão

 IKJ56425I LOGON rejected, UserId Z00716 already logged on to system S0W1       
 IKJ56400A ENTER LOGON OR LOGOFF-

**Comment by billpereira** [comment]
Os usuários caem depois de um tempo, mas você pode sempre utilizar a opcao reconnect na tela de login, depois de colocar usuario e senha vem uma tela com várias outras opções, lá vc tem a opção de reconnect
