### ISSUE TITLE
Acesso ao Cobol Lab 5

### ISSUE THREAD

**Issue by danieldamaso** [Iniciativaz/zos-workshop#67]
Por favor, no Lab 5, como faz para entrar no ambiente dos comandos COBOL? Qual o comando deve ser dado antes do Submit '###### .JCL(CBL0001J)'  ?

**Comment by AndreTorella** [comment]
Voce deve acessar o dataset do seu usuário Z00xxx.
No SDSF, digite 3.4 e prencha o dsname level com seu usuário.
Depois localize o dataset Z00xxx.jcl e digita e na frente dele.
Em seguida, localize o job CBL0001J , digite S na frente e dentro dele submit ou sub (na linha command).
