### ISSUE TITLE
Acesso ao QUIZ

### ISSUE THREAD

**Issue by mimisilre** [Iniciativaz/zos-workshop#71]
Boa tarde,

não consigo acessar o quis. Quando coloco o comando tso quiz aparece a seguinte msg:

TSO PROFILE PREFIX(YOUR_ID)
***

Após essa mensagem coloco o comando TSO PROFILE PREFIX(z#####) sendo o ##### meu ID e a sessão fecha voltando para tela inicial.

O que deve ser feito?

**Comment by AndreTorella** [comment]
Usa o comando TSO PROFILE PREFIX*

**Comment by mimisilre** [comment]
Usei este comando e acontece a mesma coisa. a mensagem some e volta para a tela inicial.

**Comment by AndreTorella** [comment]
Tenta tso profile noprefix, da enter
depois tso profile prefix(z000xx) , onde XX seu numero

**Comment by mimisilre** [comment]
No in´cio do curso eu recebi 2 e-mails com 2 ids diferentes. Com o outro Id deu certo e não apareceu a mss em questão. Acredito que seja problema no id que eu estava tentando.

Obrigada!!

**Comment by billpereira** [comment]
Conseguiu acessar?

**Comment by lsalimena** [comment]
qual o seu ID?

**Comment by lsalimena** [comment]
para acessar o quiz você precisa digitar "tso quiz" e ele vai abrir

**Comment by mimisilre** [comment]
Consegui acessar pelo id z00580. Obrigada!!
