### ISSUE TITLE
Resultado QUIZ

### ISSUE THREAD

**Issue by semonetti** [Iniciativaz/zos-workshop#72]
Fiz o quiz, porem ao verificar o meu userid Z00581 o score esta 0. Sabe se preciso fazer novamente?

**Comment by semonetti** [comment]
Obs.: Vi que o arquivo foi criado e com as respostar.

**Comment by billpereira** [comment]
provavelmente no momento que você conferiu aqui ainda não havia refletido, mas já está lá o score

**Comment by semonetti** [comment]
Muito obrigado Bill
