### ISSUE TITLE
Duas IDs

### ISSUE THREAD

**Issue by RafaelGSGoncalves** [Iniciativaz/zos-workshop#74]
Boa noite, estou com uma dúvida, comecei a assistir o workshop de introdução ao Z/OS na segunda e comecei lá usando o ID que já tinha recebido do Master The Mainframe, e vinha utilizando esse. Tive alguns problemas durante a semana e perdi algumas partes das aulas e vou tentar compensar nos slides. Mas recebi também o e-mail de vocês com outro ID para o Z/OS, é esse que devo usar para as tarefas do curso? Caso sim, tentei agora acessar esse Lab Id, mas ao colocar aquela senha padrão ZR1, ele dá senha inválida, já expirou o primeiro acesso?  

Obrigado,
Rafael Gonçalves

**Comment by billpereira** [comment]
infelizmente agora não podemos emitir um ID para você. Sugiro que você acesse o link ibm.biz/zOSclass e se cadastre para a próxima turma que ocorrerá em julho. Ela será em inglês mas você tera a oportunidade de adquirir o badge com essa oportunidade.
