### ISSUE TITLE
Lab5 Q7

### ISSUE THREAD

**Issue by PollyEler** [Iniciativaz/zos-workshop#76]
Por gentileza, como corrijo o erro do programa CBL0005. Fui no SDSF e vi a msg que o Step2 nao foi executado devido a condiçao no statement 35.
Todavia, nao consegui identificar o erro no source. Poderia me explicar. Obrigada.

**Comment by AndreTorella** [comment]
A dica é localizar o dataset Z####.source

**Comment by PollyEler** [comment]
Obrigada, vou olhar novamente. Já fui nesse dataset. Comparei a linha de report.close mas nao funcionou.

**Comment by AndreTorella** [comment]
A mensagem de erro te informa sobre a ausência do INPUT-OUTPUT.
Avalie o source do CBL0004 com o CBL0005 e localize esses dados e compare a diferença.

**Comment by PollyEler** [comment]
Muito Obrigada! Consegui com a sua ajuda! 😁😉
