### ISSUE TITLE
Lab 8 - DBCG is not operational

### ISSUE THREAD

**Issue by EddieCavic** [Iniciativaz/zos-workshop#78]
Bom dia,
Gostaria de completar o Lab 8, mas o database DBCG parece que não está disponível.

DBCG NOT OPERATIONAL, RETRY COUNT IS ZERO

Grato pela sua ajuda,
Eddie

**Comment by billpereira** [comment]
Pode tentar novamente

**Comment by EddieCavic** [comment]
Grato @billpereira 
Consegui acessar o DB2
