### ISSUE TITLE
Badge

### ISSUE THREAD

**Issue by rehgison** [Iniciativaz/zos-workshop#79]
Onde eu consigo acessar/baixar meu badge?

**Comment by lsalimena** [comment]
Você precisa passar no quiz antes. Após atingir o score mínimo de 42 acertos você será elegivel ao badge. Nós vamos emitir ao longo da semana e você o receberá no email que se cadastrou para o workshop.

**Comment by rehgison** [comment]
Já passei. Vou aguardar então. Obrigado. 

_______________
Régison Martins
Sent from my iPhone
