### ISSUE TITLE
2 usuários

### ISSUE THREAD

**Issue by Gilbertoanalistacobol** [Iniciativaz/zos-workshop#83]
Por engano, cadastrei 2 usuários no sistema. Respondi o Quiz no primeiro usuário, o de número menor. Tem algum problema, ou devo responder no último usuário, o de maior número?

**Comment by lsalimena** [comment]
Não tem problema, pode ignorar o outro ID recebido. Olhe o seu score lá na página e veja se já tem o score minimo (42) para receber o badge
