### ISSUE TITLE
Respostas do quiz leva a letra "A" ou não?

### ISSUE THREAD

**Issue by bm784k** [Iniciativaz/zos-workshop#85]
Quando respondemos o quiz no TSO, devemos colocar a letra "A" junto do numero? Por exemplo: A58, A7, A44? Ou simplesmente colocamos somente o numero? 58, 7 e 44?

**Comment by AndreTorella** [comment]
Tem que por a letra A. Tanto faz se maiúscula ou minuscula, mas SIM tem que colocar.

**Comment by lsalimena** [comment]
Sim, você precisa colocar o "a" na frente.
