### ISSUE TITLE
Erro no Quiz

### ISSUE THREAD

**Issue by Fabianobarros81** [Iniciativaz/zos-workshop#86]
Enviei meu Quiz e meu resultado foi 0, eu tenho q ter acertado pelo menos 1, a que já veio respondida né? rs

Algo deu errado no meu ID, z00084, pode verificar por favor?

**Comment by lsalimena** [comment]
O resultado sai 0 quando você ainda não terminou de responder mas eu estou rodando o script. Vou gerar novo report daqui uns 5 min. Termina aí de responder e vemos no que deu.
