### ISSUE TITLE
Score: 0

### ISSUE THREAD

**Issue by ghost** [Iniciativaz/zos-workshop#87]
Pessoal, estou com score 0 no meu quiz, sendo que ao consultar as respostas as vejo lá.
Z00339

é necessário finalizar os labs para processar a nota do quiz?

**Comment by lsalimena** [comment]
você colocou as respostas com o "a" na frente? Eu vou rodar o scrip agora e veremos

**Comment by ghost** [comment]
sim! coloquei o "a" na frente.

**Comment by lsalimena** [comment]
Ainda esta com 0... estou vendo aqui. 1 min

**Comment by lsalimena** [comment]
Resolvido. O seu ID estava preso. No próximo report já vai atualizar. * Z00339 Score: 59
