### ISSUE TITLE
invalid userid

### ISSUE THREAD

**Issue by RafaelGSGoncalves** [Iniciativaz/zos-workshop#88]
Olá! Achei que o id do curso era o mesmo que recebi do Master The Mainframe, e durante o curso estava usando esse. Para fazer o quiz precisa ser o do curso? Estou tentando me logar com o meu id do curso Z00534, com a senha inicial ZR1 mas está dando invalid userid or password...

**Comment by lsalimena** [comment]
Infelizmente agora não podemos emitir um ID para você. Sugiro que você acesse o link ibm.biz/zOSclass e se cadastre para a próxima turma do workshop que ocorrerá em julho. Ela será em inglês mas você tera a oportunidade de adquirir esse mesmo badge. Como você já vou todo o conteúdo é mais fácil.
