### ISSUE TITLE
IKJ56425I LOGON rejected, UserId Z00310 already logged on to system S0W1     

### ISSUE THREAD

**Issue by andersonnobre76** [Iniciativaz/zos-workshop#89]
Boa tarde!

Tive que reiniciar e ficou preso, caira por timeout ou terão de cancelar?

**Comment by billpereira** [comment]
ele cai por timeout, mas você não precisa esperar, pode marcar opção de reconnect na tela de login:
![image](https://user-images.githubusercontent.com/38498198/82129982-8aa5c200-979d-11ea-993c-93870ea454f1.png)
