### ISSUE TITLE
Quiz Score: 0

### ISSUE THREAD

**Issue by decollino** [Iniciativaz/zos-workshop#94]
Olá,
O resultado do meu quiz está como 0.
Sabe me dizer por quê?
Obs: Acredito que respondi as perguntas (ex: A1 ...) como deveria ser.
Obrigado.

**Comment by lsalimena** [comment]
qual o seu ID?

**Comment by decollino** [comment]
Z00252

**Comment by lsalimena** [comment]
O seu ID estava preso. 
* Z00252 Score: 51
Vai aparecer no proximo report.
