### ISSUE TITLE
Z00377 tentativa de logon com senha zr1 password incorrect

### ISSUE THREAD

**Issue by Viviaz** [Iniciativaz/zos-workshop#95]
Z00377 tentativa de logon com senha zr1 password incorrect or  user id invalid

**Comment by lsalimena** [comment]
tenta novamente, por favor. ZR1

**Comment by billpereira** [comment]
Oi Só lembrando que o IP correto é 192.86.32.67

**Comment by billpereira** [comment]
@Viviaz conseguiu?

**Comment by Viviaz** [comment]
Sim, muito obrigada

Em dom, 17 de mai de 2020 19:56, billpereira <notifications@github.com>
escreveu:
