### ISSUE TITLE
Onde estão as instruções para começar o QUIZ? Já estou logado

### ISSUE THREAD

**Issue by CastroFernandoPT** [Iniciativaz/zos-workshop#97]

**Comment by lsalimena** [comment]
Aqui: https://github.com/Iniciativaz/zos-workshop

O quiz possui 60 perguntas e respostas e você deverá identificar qual é a resposta certa para cada questão.
Para passar no quiz e poder receber o badge/certificado do workshop você precisa acertar no -mínimo 42 questões-
Você tem até domingo, dia 17/5, às 18h (GMT-3) para enviar suas respostas.
Você poderá submeter o quiz quantas vezes quiser porém sempre o último envio será computado.
Nós precisamos "corrigir" o quiz :-) Abaixo a lista de IDs com o score mais recente.
Todas as respostas deverão ser submetidas via sistema. Para abrir o quiz digite -tso quiz- no seu terminal

**Comment by CastroFernandoPT** [comment]
Não começa o quiz. Qual o comando para iniciar?

**Comment by CastroFernandoPT** [comment]
tso quiz não responde!

**Comment by CastroFernandoPT** [comment]
Ok. Comecei. Troquei de teclado! Meus teclados estão ruins! Desculpe
